// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtL9pEVFKqasXeKqQz8vvWX9sf9KwAYig',
    appId: '1:898309326529:web:9b0e5a5e9edcec7bed7640',
    messagingSenderId: '898309326529',
    projectId: 'ets-ppb-b0af4',
    authDomain: 'ets-ppb-b0af4.firebaseapp.com',
    storageBucket: 'ets-ppb-b0af4.firebasestorage.app',
    measurementId: 'G-2TXK7Z54FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnlTixmb-GjbytJh3V4ND5dDvUAWDBTJA',
    appId: '1:898309326529:android:08672d92f8bb3325ed7640',
    messagingSenderId: '898309326529',
    projectId: 'ets-ppb-b0af4',
    storageBucket: 'ets-ppb-b0af4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABOCUer41bh_WxhmFFIrVPv8e6wbIqFKg',
    appId: '1:898309326529:ios:4a4a8508708cff08ed7640',
    messagingSenderId: '898309326529',
    projectId: 'ets-ppb-b0af4',
    storageBucket: 'ets-ppb-b0af4.firebasestorage.app',
    iosBundleId: 'com.example.myinformatika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABOCUer41bh_WxhmFFIrVPv8e6wbIqFKg',
    appId: '1:898309326529:ios:4a4a8508708cff08ed7640',
    messagingSenderId: '898309326529',
    projectId: 'ets-ppb-b0af4',
    storageBucket: 'ets-ppb-b0af4.firebasestorage.app',
    iosBundleId: 'com.example.myinformatika',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtL9pEVFKqasXeKqQz8vvWX9sf9KwAYig',
    appId: '1:898309326529:web:52a1100055b183dded7640',
    messagingSenderId: '898309326529',
    projectId: 'ets-ppb-b0af4',
    authDomain: 'ets-ppb-b0af4.firebaseapp.com',
    storageBucket: 'ets-ppb-b0af4.firebasestorage.app',
    measurementId: 'G-6CDJPLPV62',
  );
}
